### ISSUE TITLE
Report of Bunny deploys via CLI failing (UI fine)

### ISSUE THREAD

**Issue by leonstafford** [leonstafford/static-html-output#142]
thread: https://staticword.press/t/error-using-wp-cli/237

**Comment by snibbo71** [comment]
Heya,
    So I've investigated this a little myself after all.

Line 43 of static-html-plugin/src/BunnyCDN.php has the following;

if ( defined( 'WP_CLI' ) ) {
    return;
}

I cannot see the logic behind this since the next 2 lines provide extra configuration that will be needed whether it's the GUI or CLI. So I commented that bit out and now it's working nicely.

Let me know if there's something I've missed though!
Ta,
Steve

**Comment by leonstafford** [comment]
Many thanks, @snibbo71! I've pushed up the change. I haven't done a thorough test of latest code, but at least that part should be good now.
